### ISSUE TITLE
Wallbase with tags

### ISSUE THREAD

**Issue by nomi00001** [sevensins/Wallbase-Downloader#11]
Hello sir,
first thanks alot for the amazing script,
sir this script download wallpapers with there id example ( wallpaper-2371145.jpg ) is there any way that it download with its tags example ( wallpaper-cute-cat.jpg or just cute-cat.jpg )

**Comment by macearl** [comment]
I just implemented this function (quick and dirty)

I marked it as experimental because i didnt test it that much (around 400 wallpapers) and because some wallpapers dont even have tags that means it would rename them to just .jpg .png or .gif also if some Wallpaper have the same tags the script would override the old one.

Also keep in mind that some wallpapers have a lot of tags this will result in very long filenames.

Overall i would not recommend using this

**Comment by nomi00001** [comment]
Thanks for reply if some wallpapers dont have tags is it possible that it download with there id and if some wallpapers have same tags is it possible that it download like ( cute-cat.jpg  cute-cat2.jpg ) and for long tags with comes with long filename hope there will be also something for it.
i just want to create a website and i want the url not to be with id i want url like domain.com/cute-cat.jpg
and is there any other way to contect you i want to show u a website and a script which i cant show here

**Comment by macearl** [comment]
Its probably possible its just a matter of checking if the variable filename is empty and if it is change it to the id.

For duplicates its just a check if the file already exists and if it does add a number (and if that file also exists increment the number and so on)

Its not really hard to implement but it would take quite some time and im quite busy in the moment i will take a look at it when i have the time (could be a few days or a few months)

If you want to take a look at it yourself you would only need to add some stuff in line 482

**Comment by nomi00001** [comment]
Thanks your reply really help me alot,
BTW is there any other way to contact you i mean you have any website
