### ISSUE TITLE
Script error Section 13

### ISSUE THREAD

**Issue by spinoziste** [sevensins/Wallbase-Downloader#6]
First : Thank you for your script it's very usefull ;)

I still have a problem with it . 

I typed my username and password in the wallbase.sh but when i enter :
sh wallbase.sh 

wallbase.sh: 388: wallbase.sh: function: not found
Please check the needed Options for NSFW/New Content (username and password)

For further Information see Section 13

Press any key to exit
wallbase.sh: 396: read: arg count

I am n00b certainly but login/password seems to be in the right place

OS : Linux/Ubuntu

Thank you for your help . :)

**Comment by macearl** [comment]
Hi,

please post your config section and confirm that your username/password section looks like this, lets say your username is: user12345 and your password is: password then it has to look like this:

```
# See Section 13
# Enter your Username
USER="user12345"
# Enter your password
PASS="password"
```

**Comment by spinoziste** [comment]
Thank you for helping the n00b i am ;)

**# See Section 13**
**# Enter your Username**
**USER="darky_lazy"**
**# Enter your password**
**PASS="mypasswordhere"**

Is it because of the : "_" ?

**Comment by macearl** [comment]
No the "_" works fine on my system.
And i actually meant the other config section, this:

```
#################################
###   Configuration Options   ###
#################################

# For accepted values see Section 6
MAX_RANGE=40
# For accepted values of resolution see Section 1
RESOLUTION=1920x1080
# For accepted values of aspect ratio see Section 2
ASPECTRATIO=1.77
# For accepted values of category see Section 3
CATEGORY=111
# For accepted values of topic see Section 4
TOPIC=123
# For accepted values for SIZE see Section 5
SIZE=gteq
# For accepted Thumbnails per page see Section 6
THPP=20
# For download location see Section 7
LOCATION=~/Pictures/Wallpaper/test
# Best of : see Section 8
TIME=0
# For Types see Section 9
TYPE=1
# For order Options see Section 10
ORDER=relevance
# See Section 11
ORDER_TYPE=desc
# See Section 12
QUERY="$1"
# See Section 14
COLLECTION=-1
# See Section 15
CATEGORIZE=0
# See Section 16
WP_RANGE_START=0
WP_RANGE_STOP=0
# See Section 17
Related=0

#################################
### End Configuration Options ###
#################################
```

**Comment by spinoziste** [comment]
The configuration seems to be good . 

I still have the same error .

**Comment by macearl** [comment]
What did you try now?

please post your config section.
I cant try to reconstruct the error if i dont have all the data.

EDIT:

Just thought of something different could you try running it with this command:

```
bash wallbase.sh
```

EDIT2:

just did some research Ubuntu changed their standard /bin/sh from bash to dash a while ago thats why you get this error. You can fix this by changing your command to

```
./wallbase.sh
```

or as mentioned in EDIT to:

```
bash wallbase.sh
```

The Problem right now is that the script isnt fully posix compatible. I havent looked much into the posix standard and there are some disadvantages, especially with functions and local aliases. If I have the time i will look further into it and maybe convert the Script to POSIX standard.

Let me know if your Problem is fixed.

**Comment by spinoziste** [comment]
The problem is solved . I should did some research by myself . Thank you very much for helping me and for this very sympathic script . 

Best regards .
Spino .
